careerbi_gold:
  
  target: dev 
  
  outputs:
    # 💻 "Thế giới" 1: Cho MÁY MAC của bạn
    dev:
      type: postgres
      host: localhost
      user: careerbi_user
      pass: careerbi_password
      port: 5432
      dbname: careerbi
      schema: gold_dev
      threads: 4

    # 🐳 "Thế giới" 2: Cho AIRFLOW (Docker)
    prod:
      type: postgres
      host: postgres
      user: careerbi_user
      pass: careerbi_password
      port: 5432
      dbname: careerbi
      schema: gold
      threads: 4